config/urls.py
from django.contrib import admin
from django.urls import path,include,reverse_lazy,reverse
from django.shortcuts import render,HttpResponse
from django.views.generic import TemplateView
from core.log.utils import MyLoginRequiredMixin
from core.user.models import User
from django.contrib.auth.models import Group,Permission
from django.views.generic.base import RedirectView
def init_groups_permission_sueruser(init=False):
    context=""
    try:
        bool=True
        
        bool= not (init==True and Group.objects.all().exists()) 
        
        if bool==True:
            l={
                'Developer':[
                    'is_development',
                    'view_user',
                    'add_user',
                    'change_user',
                    'delete_user',
                    'act_desact_user',
                    'view_performance',
                    'view_binnacle',
                    'view_config',
                    'modbus_perm'
                ],
                'Admin':[
                    'is_admin',
                    'view_user',
                    'add_user',
                    'change_user',
                    'delete_user',
                    'act_desact_user',
                    'view_performance',
                    'modbus_perm',
                ],
                'Guest':[
                    'is_guest',
                ]
            }
            for gn,pl in l.items():
                try:
                    g=Group.objects.get_or_create(name=gn)[0]
                    g.permissions.clear()
                    context+="{}<br>".format(gn)
                    for pn in pl: 
                        try:
                            p=Permission.objects.get(codename=pn)
                            context+="<dd>{}</dd><br>".format(pn)
                            g.permissions.add(p)
                        except Exception as e:
                            context+="<br>Error:{}:    {}<br><br>".format(e,pn)
                except Exception as e:
                    context+="<br>Error:{}:    {}<br><br>".format(e,gn)
            u=User.objects.get_or_create(
                first_name="Super User",
                username="superuser",
                is_superuser=True,
                is_staff=True,
            )
            uu=u[1]
            u=u[0]
            if uu==True:
                u.set_password('superuser')
                u.save()
            u.groups.add(Group.objects.get(name="Developer"))
            context+="{} Super User<br>".format("Created" if uu==True else "See",gn)
            context+="<br><a href='{}' role='btn'>Volver</a>".format(reverse_lazy('process'))
    except:
        pass
    return context
    
init_groups_permission_sueruser(True)

class QR(TemplateView):
    template_name='QR.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        home_qr_url=self.request.build_absolute_uri(reverse('prot'))
        context["home_qr_url"] = home_qr_url
        return context

class InitView(TemplateView):
    def get(self,request):
        if request.user.is_superuser:
            return HttpResponse(init_groups_permission_sueruser())
        return render(request,'403.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('init/',InitView.as_view()),
    path('QR/',QR.as_view(),name='qr'),
    path('',RedirectView.as_view(pattern_name="prot")),
    path('log/',include('core.log.urls')),
    path('user/',include('core.user.urls')),
    path('conf/',include('core.conf.urls')),
    path('perf/',include('core.perf.urls')),
    path('binn/',include('core.binn.urls')),
    path('prot/',include('core.prot.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/binn/urls.py
from django.urls import path
from .views import BinnacleView

urlpatterns = [
    path('',BinnacleView.as_view(),name='binn'),
    path('<str:iden>/',BinnacleView.as_view(),name='binn_s'),
]

core/binn/models.py
from django.db import models

# Create your models here.

IDENTF = [
    ("I", "Información"),
    ("R", "Reportes"),
    ("A", "Advertencias"),
    ("E", "Error"),
]
class BinnacleMessages(models.Model):
    identifier=models.CharField(max_length=1,choices=IDENTF)
    identifier_message=models.CharField(max_length=50)
    reason=models.CharField(max_length=50)
    timedate=models.DateTimeField(auto_now_add=True)

core/binn/views.py
from django.shortcuts import render
from core.log.utils import MyLoginRequiredMixin
from django.views.generic import ListView
from .models import BinnacleMessages
# Create your views here.

class BinnacleView(MyLoginRequiredMixin,ListView):
    template_name="binn.html"
    model=BinnacleMessages
    permission_required='view_binnacle'
    
    def dispatch(self, request, *args, **kwargs):
        self.kwargs['iden']=kwargs.get('iden')
        return super().dispatch(request, *args, **kwargs)
    
    
    def get_context_data(self, **kwargs) :
        context=super().get_context_data(**kwargs)
        iden:str=self.kwargs.get('iden')
        if iden in ["I","R","A","E"] :
            context['object_list']=BinnacleMessages.objects.filter(identifier=iden)
            context['iden']=iden
            
        
        context['title']="Bitácora de Errores"
        context['i_count']=BinnacleMessages.objects.filter(identifier='I').count()
        context['r_count']=BinnacleMessages.objects.filter(identifier='R').count()
        context['a_count']=BinnacleMessages.objects.filter(identifier='A').count()
        context['e_count']=BinnacleMessages.objects.filter(identifier='E').count()
        return context
    

core/binn/templates/binn.html
{% extends '_list.html' %}

{% block content_before %}
    <div class="container">
        <div class="h2 mb-4">Bitácora</div>
        <div class="row">
            <div class="col-3">
                <div class="small-box bg-{% if not iden or iden == "I"  %}info{% else %}dark{% endif %}">
                    <div class="inner">
                    <h3>{{i_count}}</h3>
                    <p>Información</p>
                    </div>
                    <div class="icon">
                    <i class="fas fa-solid fa-circle-info"></i>
                    </div>
                    <a href="{% url 'binn_s' 'I' %}" class="small-box-footer">Más Información  <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-3">
                <div class="small-box bg-{% if not iden or iden == "R"  %}success{% else %}dark{% endif %}">
                    <div class="inner">
                    <h3>{{r_count}}</h3>
                    <p>Reportes</p>
                    </div>
                    <div class="icon">
                    <i class="fas fa-regular fa-clipboard"></i>
                    </div>
                    <a href="{% url 'binn_s' 'R' %}" class="small-box-footer">Más Información  <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-3">
                <div class="small-box bg-{% if not iden or iden == "A"  %}warning{% else %}dark{% endif %}">
                    <div class="inner">
                    <h3>{{a_count}}</h3>
                    <p>Advertencias</p>
                    </div>
                    <div class="icon">
                        <i class="fas fa-solid fa-circle-exclamation"></i>
                    </div>
                    <a href="{% url 'binn_s' 'A' %}" class="small-box-footer">Más Información  <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <div class="col-3">
                <div class="small-box bg-{% if not iden or iden == "E"  %}danger{% else %}dark{% endif %}">
                    <div class="inner">
                    <h3>{{e_count}}</h3>
                    <p>Errores</p>
                    </div>
                    <div class="icon">
                    <i class="fas fa-solid fa-triangle-exclamation"></i>
                    {% comment %} <i class="ion ion-bag"></i> {% endcomment %}
                    </div>
                    <a href="{% url 'binn_s' 'E' %}" class="small-box-footer">Más Información  <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            
        </div>
    </div>
{% endblock %}

{% block columns %}
        <th scope="col">Tipo</th>
        <th scope="col">Identificación</th>
        <th scope="col">Motivo</th>
        <th scope="col">Fecha y Hora</th>
{% endblock %}

{% block rows %}
    {% for binnacle in object_list %}
        <tr class="text-center align-items-center">
            <td scope="row">
                <span class=" badge bg-{% if binnacle.identifier == 'I' %}info{% elif binnacle.identifier == 'R' %}success{% elif binnacle.identifier == 'A' %}warning{% else %}danger{% endif %}">
                    <div class="h6 m-0 ">
                        {{binnacle.get_identifier_display}}
                    </div>
                </span>
            </td>
            <td scope="row">{{binnacle.identifier_message}}</td>
            <td scope="row">{{binnacle.reason}}</td>
            <td scope="row">{{binnacle.timedate}}</td>
        </tr>
    {% endfor %}

{% endblock %}

    {% block box_footer_buttons %}
        {% if iden %}
            <a href="{% url 'binn' %}" class="btn btn-{% if iden == "I" %}info{% elif iden == "R" %}success{% elif iden == "A" %}warning{% else %}danger{% endif %} btn-flat">
                <i class="fas fa-sync-alt"></i> Quitar Filtro
            </a>
        {% else %}
            {{ block.super }}
        {% endif %}
    {% endblock %}